apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev

bases:
  - ../../base/sample-nginx

commonLabels:
  environment: dev

replicas:
  - name: sample-nginx
    count: 1
