apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-staging

bases:
  - ../../base/sample-nginx

commonLabels:
  environment: staging

replicas:
  - name: sample-nginx
    count: 2
