apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/kustomization.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-same-namespace.yaml
  - rbac/platform-team-rbac.yaml
  - rbac/is-team-rbac.yaml
  - projects/applications.yaml
  - projects/platform-services.yaml
