apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/environments.yaml
  - rbac/platform-team-rbac.yaml
  - rbac/is-team-rbac.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-same-namespace.yaml

commonLabels:
  managed-by: gitops
  component: infrastructure
