apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-monitoring

resources:
  - grafana-dashboards-configmap.yaml

configMapGenerator:
  - name: grafana-dashboard-provider
    files:
      - dashboards.yaml
