apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-production

bases:
  - ../../base/sample-nginx

commonLabels:
  environment: production

replicas:
  - name: sample-nginx
    count: 3
